from .nodes.zmongo_session_manager_nodes import (
    NODE_CLASS_MAPPINGS as SESSION_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as SESSION_NODE_DISPLAY_NAME_MAPPINGS,
)
from .nodes.zmongo_image_bridge_nodes import (
    NODE_CLASS_MAPPINGS as IMAGE_BRIDGE_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as IMAGE_BRIDGE_NODE_DISPLAY_NAME_MAPPINGS,
)
from .nodes.zmongo_image_loader_nodes import (
    NODE_CLASS_MAPPINGS as IMAGE_LOADER_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as IMAGE_LOADER_NODE_DISPLAY_NAME_MAPPINGS,
)

NODE_CLASS_MAPPINGS = {
    **SESSION_NODE_CLASS_MAPPINGS,
    **IMAGE_BRIDGE_NODE_CLASS_MAPPINGS,
    **IMAGE_LOADER_NODE_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **SESSION_NODE_DISPLAY_NAME_MAPPINGS,
    **IMAGE_BRIDGE_NODE_DISPLAY_NAME_MAPPINGS,
    **IMAGE_LOADER_NODE_DISPLAY_NAME_MAPPINGS,
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]